#!/bin/sh

catalogfile="src/js/iqons-catalog.js"

rm $catalogfile
echo "const IqonsCatalog = { " > $catalogfile

rm -rf tmp
mkdir tmp

symbolize ()
{
folder=$1
index=0
foldername=$(basename "$folder")
foldername="${foldername%.*}"
filenames="$foldername : ["
for file in $folder*
do
    index=$(($index+1))

    filename=$(basename "$file")
    filename="${filename%.*}"

    filenames+="'$filename',"


    assetname="$foldername"
    assetname+="-$index"
    sed -i 's/svg xmlns="http:\/\/www.w3.org\/2000\/svg"/symbol id="'$assetname'"/g' $file
    sed -i 's/\/svg/\/symbol/g' $file
    sed -i 's/#11AA11/currentColor/g' $file
    sed -i 's/#1A1/currentColor/g' $file
    sed -i 's/#FE1/inherit/g' $file
    sed -i 's/#FE0/inherit/g' $file
    sed -i 's/#FFED00/inherit/g' $file
done
echo "$2 : $index features"
filenames+="],"
echo $filenames >> $catalogfile
}


mkdir tmp/face
./node_modules/svgo/bin/svgo -f src/svg/face -o tmp/face --config=config.yml

mkdir tmp/side
./node_modules/svgo/bin/svgo -f src/svg/side -o tmp/side --config=config.yml

mkdir tmp/top
./node_modules/svgo/bin/svgo -f src/svg/top -o tmp/top --config=config.yml

mkdir tmp/bottom
./node_modules/svgo/bin/svgo -f src/svg/bottom -o tmp/bottom --config=config.yml

symbolize tmp/face/ "face"
symbolize tmp/side/ "side"
symbolize tmp/top/ "top"
symbolize tmp/bottom/ "bottom"

echo "}" >> $catalogfile


echo '<svg xmlns="http://www.w3.org/2000/svg">' > dist/iqons.min.svg
for i in `find tmp -name '*.svg'` ; do cat $i ; echo "" ; done >> dist/iqons.min.svg
echo '</svg>' >> dist/iqons.min.svg

rm -rf tmp

uglifyjs --compress --mangle -o dist/iqons.min.js -- src/js/iqons.js