export const WordsCatalog = {
color: [
    "Orange",
    "Red",
    "Yellow",
    "Indigo",
    "Light Blue",
    "Purple",
    "Teal",
    "Pink",
    "Light Green",
    "Brown"
    // TODO Better names for Light Colors?
],
face: [
    ["Cute", "Whiskered", "Proud", "Purring", "Straying", "Meowing", "Cat", "Kitten", "Tomcat"],
    ["Red-Nosed", "Comical", "Clownish", "Entertaining", "Amusing", "Hoaxing", "Bubble-Nose", "Rudolph", "Clown"],
    ["Shocked", "Sad", "Unhappy", "Whining", "Crying", "Weeping", "Crybaby", "Whiner", "Whimperer"],
    ["Ironic", "Weird", "Jokey", "Winking", "Blinking", "Squinting", "Eye-Cramp", "Emoji", "Smiley"],
    ["Money-Hungry", "Greedy", "Capitalist", "Money-Loving", "Moneymaking", "Investing", "Banker", "Moneymaker", "Entrepreneur"],
    ["Bloodthirsty", "Bloody", "Undead", "Bloodsucking", "Biting", "Killing", "Vampire", "Dracula", "Bloodsucker"],
    ["Duckfaced", "Short-Billed", "Bird-like", "Chattering", "Cackling", "Quacking", "Drake", "Duck", "Goose"],
    ["Evil", "Sly", "Vicious", "Cursing", "Cunning", "Intriguing", "Villain", "Baddie", "Bully"],
    ["Aroused", "Horny", "Infatuated", "Loving", "Admiring", "Desiring", "Lover", "Romantic", "Romeo"],
    ["Surprised", "Dead", "Lifeless", "Decaying", "Dying", "Fading", "Ghoul", "Zombie", "Corpse"],
    ["Mustached", "Bearded", "Prickly", "Grooming", "Shaving", "Trimming", "Mustache", "Barber", "Shakers"],
    ["Bad-Eyed", "Four-Eyed", "Nerdy", "Squinting", "Reading", "Educating", "Nerd", "Geek", "Wonk"],
    ["One-Eyed", "Monocular", "Monstrous", "Eyeballing", "Staring", "Gaping", "Mutant", "Cyclops", "Freak"],
    ["Cute", "Tame", "Fluffy", "Snuggling", "Cuddling", "Romping", "Panda", "Bear", "Animal"],
    ["Tropical", "Noisy", "Exotic", "Parroting", "Chirping", "Tweeting", "Parrot", "Budgie", "Birdie"],
    ["Pig-Nosed", "Piggy", "Pig-Headed", "Oinking", "Wallowing", "Sniffling", "Sow", "Boar", "Swine"],
    ["Eye-Patched", "Gruff", "Wounded", "Eye-Catching", "Scowling", "Frowning", "Rover", "McEyepatch", "Buccaneer"],
    ["Happy", "Amused", "Jolly", "Loling", "Giggling", "Laughing", "Laugher", "Giggler", "Troll"],
    ["Amazed", "Curious", "Avid", "Sparkling", "Staring", "Gaming", "Starface", "Fan", "Wonderkid"],
    ["Swaggy", "Funky", "Cool", "Sunbathing", "Chilling", "Holding", "Styler", "Fashionista", "Celebrity"],
    ["Funny", "Goofy", "Absurd", "Joking", "Window-Licking", "Slavering", "Joker", "Clown", "Tongue"],
],
side : [
    ["Astronomical", "Artificial", "Metallic", "Transmitting", "Orbiting", "Connecting", "Satellite", "Cyborg", "Drone"],
    ["Shot", "Hit", "Pierced", "Shooting", "Suffering", "Enduring", "Amateur-Archer", "Arrow", "Shooter"],
    ["Drunk", "Sober", "Wasted", "Brewing", "Sipping", "Partying", "Bavarian", "Beer-Fan", "Inebriate"],
    ["Protective", "Aggressive", "Gloved", "Boxing", "Fighting", "Slamming", "Boxer", "Streetfighter", "Fighter"],
    ["Horned", "Spiky", "Deadly", "Stabbing", "Sticking", "Pricking", "Viking", "Savage", "Barbarian"],
    ["Pointy-Eared", "Elfish", "Puckish", "Ear-Cocking", "Listening", "Eavesdropping", "Elf", "Trekkie", "Vulcan"],
    ["Pincerlike", "Protective", "Scuttling", "Pinching", "Snatching", "Squeezing", "Crab", "Lobster", "Crawfish"],
    ["Magic", "Occult", "Eerie", "Conjuring", "Spell-Casting", "Jinxing", "Wizard", "Warlock", "Sorcerer"],
    ["Two-Petaled", "Sustainable", "Organic", "Flowering", "Flourishing", "Blooming", "Flower", "Plant", "Sprout"],
    ["Sporty", "Fit", "Macho", "Touch-Downing", "Scoring", "Tackling", "Quarterback", "Coach", "Team-Captain"],
    ["Hungry", "Empty-Bellied", "Craving", "Munching", "Snacking", "Eating", "Foodie", "Big Eater", "Gourmet"],
    ["Big-Eared", "Bat-Eared", "Keen-Eared", "Ear-Lending", "Overhearing", "Ear-Wiggling", "Listener", "Monster-Ear", "Hearer"],
    ["Pumped", "Ripped", "Muscly", "Weight-Lifting", "Training", "Exercising", "Bodybuilder", "Iron-Pumper", "Muscle Man"],
    ["Talky", "Chatty", "Talkative", "Mom-Calling", "Dialing", "Ringing", "Caller", "Phone-Addict", "Telephoner"],
    ["Triumphant", "Peaceful", "Victorious", "Selfie-Making", "Posing", "Celebrating", "Poser-Kid", "Winner", "Peace-Actvist"],
    ["Athletic", "Olympic", "Competitive", "Serving", "Defeating", "Sporting", "Player", "Tennis-Pro", "Athlete"],
    ["Twiggy", "Biological", "Leafy", "Sprouting", "Blossoming", "Budding", "Ent", "Tree", "Bush"],
    ["Heavenly", "Feathered", "Graceful", "Flapping", "Winging", "Flailing", "Angel", "Bird", "Aviator"],
    ["Busy", "Efficient", "Productive", "Multitasking", "High-Performing", "Consulting", "Manager", "Multitasker", "Headset-Guy"],
    ["Fishy", "Maritime", "Aquatic", "Swimming", "Fin-Waving", "Bathing", "Blowfish", "Fish", "Whale"],
    ["Hot", "Warm", "Steamy", "Whistling", "Boiling", "Piping", "Teapot", "Kettle", "Pot"],
],
top : [
    ["Bewigged", "Uncombable", "Curly", "Hair-Dyeing", "Blow-Drying", "Shampooing", "Granny", "Perm", "Wig"],
    ["Antenna-Headed", "Connected", "Extrinsic", "Receiving", "Signalling", "Scouting", "Alien", "Martian", "Visitor"],
    ["Juicy", "Fresh", "Ripe", "Nourishing", "Filling", "Refreshing", "Pear", "Apple", "Fruit"],
    ["Sun-Protected", "Shadowed", "Oriental", "Sun-Fearing", "Working", "Harvesting", "Tourist", "Fisherman", "Farmer"],
    ["Primitive", "Bony", "Wild", "Bone-Collecting", "Man-Eating", "Scoring", "Galoot", "Savage", "Caveman"],
    ["Gastronomic", "Culinary", "Flavorful", "Cooking", "Baking", "Frying", "Chef", "Cook", "Foodie"],
    ["Free", "Outdoor", "Country", "Cattle-Driving", "Lassoing", "Riding", "Rancher", "Texan", "Herder"],
    ["Oldfashioned", "Sophisticated", "Traditional", "Hat-Wearing", "Gun-Slinging", "Intimidating", "Mafioso", "Mobster", "Gangster"],
    ["Medical", "Caring", "Analytical", "Examining", "Healing", "Curing", "Doctor", "Dentist", "Medic"],
    ["Drippy", "Sweaty", "Wet", "Splashing", "Leaking", "Dripping", "Splash", "Droplet", "Raindrop"],
    ["Allegedly-Dead", "Iconic", "Reborn", "Rock'n'Rolling", "Singing", "Dancing", "Elvis", "Rockabilly", "Imitator"],
    ["Holy", "Worshipped", "Divine", "Blessing", "Gleaming", "Redeeming", "Saint", "Angel", "Halo"],
    ["Native", "Indigenous", "Aboriginal", "Defending", "Feather-Wearing", "Smoke-signaling", "Hippie", "Chief", "Warrior"],
    ["Crowned", "Godlike", "Monarchical", "Ruling", "Reigning", "Commanding", "King", "Monarch", "Prince"],
    ["Wise", "Powerful", "Loyal", "King-Serving", "Fighting", "Advising", "Musketeer", "Sorcerer", "Magus"],
    ["Psychedelic", "Edible", "Poisonous", "Mesmerizing", "Intoxicating", "Befuddling", "Mushroom", "Agaric", "Fungus"],
    ["Uniformed", "Official", "Dutiful", "Stripping", "Patroling", "Arresting", "Officer", "Stripper", "Deputee"],
    ["Noble", "Fairy", "Royal", "Charming", "Dreaming", "Inspiring", "Princess", "Madam", "Queen"],
    ["Edgy", "Rowdy", "Crazy", "Revolting", "Rioting", "Provoking", "Punk", "Outlaw", "Anarchist "],
    ["Fabulous", "Mythical", "Imaginary", "Amazing", "Fascinating", "Enchanting", "Unicorn", "Chimera", "Narwhal"],
    ["Cold", "Chilly", "Winterly", "Freezing", "Quivering", "Shivering", "Scandinavian", "Bobble", "McBobbleHat"],
],
bottom : [
    ["Light", "Fun", "Helium", "Floating", "Flying", "Swelling", "Balloon", "Ball", "Aerostat"],
    ["Four-Toed", "Shoeless", "Barefoot", "Wandering", "Hiking", "Lumbering", "Hobbit", "Wanderer", "Hiker"],
    ["Clawed", "Birdlike", "Aerial", "Waddling", "Clawing", "Toddling", "Birdman", "Birdie", "Harpy"],
    ["Elegant", "Overdressed", "Classy", "Impressive", "Posing", "Imposing", "Nobleman", "Suit", "Gentleman"],
    ["Scary", "Uncanny", "Monstrous", "Crawling", "Scuttling", "Creeping", "Spider", "Spiderman", "Tarantula"],
    ["Fishtailed", "Finned", "Overfished", "Mermaiding", "Diving", "Splashing", "Mermaid", "Ariel", "Sea-Cow"],
    ["Homegrown", "Leafy", "Lush", "Growing", "Gardening", "Grass-rooting", "Flower", "Seed", "Spirit"],
    ["Rhythmic", "Musical", "Tuneful", "Rocking", "Jamming", "Shredding", "Musician", "Guitarist", "Rocker"],
    ["Graceful", "High-Heeled", "Sexy", "Balancing", "Seducing", "Sashaying", "Lady", "Drag", "Signora"],
    ["Weightless", "Zero-G", "Light", "Levitating", "Floating", "Hovering", "Ghost", "Levitator", "Hover-Ball"],
    ["Tentacled", "Eight-Limbed", "Slimy", "Slithering", "Sliding", "Skidding", "Octopus", "Tentacles", "Alien"],
    ["Bulb-Shaped", "Bright", "Shiny", "Idea-Giving", "Glowing", "Illuminating", "Bulb", "Socket", "Luminary"],
    ["Peg-Legged", "Wooden", "Tripling", "Limping", "Hobbling", "Stumbling", "Pirate", "Hobble", "Veteran"],
    ["Hyperactive", "Active", "Energetic", "Jumping", "Hopping", "Skipping", "Bouncy-Ball", "Doer", "Motivator"],
    ["Teenage", "Fly", "Skillful", "Riding", "Skateboarding", "Kickflipping", "Amateur", "Pro-Skater", "Skateboarder"],
    ["Old-school", "Childish", "Weird", "Skating", "Rolling", "Spinning", "Fly ", "Skater", "80s-Kid"],
    ["Fast", "Downhill", "Alpine", "Skiing", "Gliding", "Speeding", "Skier", "Ski-Instructor", "Snow-Slider"],
    ["Skillful", "Quick", "Vigorous", "Kicking", "Dribbling", "Scoring", "Striker", "Goalkeeper", "Kicker"],
    ["Outboxed", "Jumpy", "Bouncy", "Surprising", "Flip-Flopping", "Trolling", "Surprise", "Jester", "Joker"],
    ["Jaunty", "Light-Footed", "Agile", "Wandering", "Strolling", "Running", "Rambler", "Flaneur", "Pedestrian"],
    ["Wheeled", "Fast", "Mobile", "Driving", "Cruising", "Drifting", "Wheelie", "Ride", "Car"],
],
};

WordsCatalog.ADJECTIVE0 = 0;
WordsCatalog.ADJECTIVE1 = 1;
WordsCatalog.ADJECTIVE2 = 2;
WordsCatalog.VERB0      = 3;
WordsCatalog.VERB1      = 4;
WordsCatalog.VERB2      = 5;
WordsCatalog.NOUN0      = 6;
WordsCatalog.NOUN1      = 7;
WordsCatalog.NOUN2      = 8;
