// removeIf(production)
import { colorNames } from './color-names.js';
// endRemoveIf(production)

export const WordCatalog = {
color: colorNames,
face: [
    ['Cute', 'Whiskered', 'Proud', 'Purring', 'Straying', 'Meowing', 'Cat', 'Kitten', 'Tomcat'],
    ['Red-Nosed', 'Comical', 'Clownish', 'Entertaining', 'Amusing', 'Hoaxing', 'Bubble-Nose', 'Rudolph', 'Clown'],
    ['Shocked', 'Sad', 'Unhappy', 'Whining', 'Crying', 'Weeping', 'Crybaby', 'Whiner', 'Whimperer'],
    ['Ironic', 'Weird', 'Jokey', 'Winking', 'Blinking', 'Squinting', 'Eye-Cramp', 'Emoji', 'Smiley'],
    ['Thrifty', 'Frugal', 'Self-Made', 'Money-Loving', 'Moneymaking', 'Investing', 'Banker', 'Moneymaker', 'Entrepreneur'],
    ['Bloodthirsty', 'Bloody', 'Undead', 'Bloodsucking', 'Biting', 'Killing', 'Vampire', 'Dracula', 'Bloodsucker'],
    ['Duckfaced', 'Short-Billed', 'Bird-like', 'Chattering', 'Cackling', 'Quacking', 'Drake', 'Duck', 'Goose'],
    ['Evil', 'Sly', 'Vicious', 'Cursing', 'Cunning', 'Intriguing', 'Villain', 'Baddie', 'Bully'],
    ['Romantic', 'Admiring', 'Infatuated', 'Loving', 'Admiring', 'Desiring', 'Lover', 'Romantic', 'Romeo'],
    ['Surprised', 'Dead', 'Lifeless', 'Decaying', 'Dying', 'Fading', 'Ghoul', 'Zombie', 'Corpse'],
    ['Mustached', 'Bearded', 'Prickly', 'Grooming', 'Shaving', 'Trimming', 'Mustache', 'Barber', 'Shakers'],
    ['Bad-Eyed', 'Four-Eyed', 'Nerdy', 'Squinting', 'Reading', 'Educating', 'Nerd', 'Geek', 'Wonk'],
    ['One-Eyed', 'Monocular', 'Monstrous', 'Eyeballing', 'Staring', 'Gaping', 'Mutant', 'Cyclops', 'Freak'],
    ['Cute', 'Tame', 'Fluffy', 'Snuggling', 'Cuddling', 'Romping', 'Panda', 'Bear', 'Animal'],
    ['Tropical', 'Noisy', 'Exotic', 'Parroting', 'Chirping', 'Tweeting', 'Parrot', 'Budgie', 'Birdie'],
    ['Pig-Nosed', 'Piggy', 'Pig-Headed', 'Oinking', 'Wallowing', 'Sniffling', 'Sow', 'Boar', 'Swine'],
    ['Eye-Patched', 'Gruff', 'Wounded', 'Eye-Catching', 'Scowling', 'Frowning', 'Rover', 'McEyepatch', 'Buccaneer'],
    ['Happy', 'Amused', 'Jolly', 'Loling', 'Giggling', 'Laughing', 'Laugher', 'Giggler', 'Troll'],
    ['Amazed', 'Curious', 'Avid', 'Sparkling', 'Staring', 'Gaming', 'Starface', 'Fan', 'Wonderkid'],
    ['Swaggy', 'Funky', 'Cool', 'Sunbathing', 'Chilling', 'Holding', 'Styler', 'Fashionista', 'Celebrity'],
    ['Funny', 'Goofy', 'Absurd', 'Joking', 'Window-Licking', 'Bold', 'Joker', 'Clown', 'Tongue'],
],
side : [
    ['Astronomical', 'Artificial', 'Metallic', 'Transmitting', 'Orbiting', 'Connecting', 'Satellite', 'Cyborg', 'Drone'],
    ['Shot', 'Hit', 'Pierced', 'Shooting', 'Suffering', 'Enduring', 'Amateur-Archer', 'Arrow', 'Shooter'],
    ['Drunk', 'Sober', 'Wasted', 'Brewing', 'Sipping', 'Partying', 'Bavarian', 'Beer-Fan', 'Inebriate'],
    ['Protective', 'Punchy', 'Gloved', 'Boxing', 'Fighting', 'Slamming', 'Boxer', 'Streetfighter', 'Fighter'],
    ['Horned', 'Spiky', 'Deadly', 'Stabbing', 'Sticking', 'Pricking', 'Viking', 'Savage', 'Barbarian'],
    ['Pointy-Eared', 'Elfish', 'Puckish', 'Ear-Cocking', 'Listening', 'Eavesdropping', 'Elf', 'Trekkie', 'Vulcan'],
    ['Pincerlike', 'Protective', 'Scuttling', 'Pinching', 'Snatching', 'Squeezing', 'Crab', 'Lobster', 'Crawfish'],
    ['Magic', 'Occult', 'Eerie', 'Conjuring', 'Spell-Casting', 'Jinxing', 'Wizard', 'Warlock', 'Sorcerer'],
    ['Two-Petaled', 'Sustainable', 'Organic', 'Flowering', 'Flourishing', 'Blooming', 'Flower', 'Plant', 'Sprout'],
    ['Sporty', 'Fit', 'Macho', 'Touch-Downing', 'Scoring', 'Tackling', 'Quarterback', 'Coach', 'Team-Captain'],
    ['Hungry', 'Empty-Bellied', 'Craving', 'Munching', 'Snacking', 'Eating', 'Foodie', 'Big Eater', 'Gourmet'],
    ['Big-Eared', 'Bat-Eared', 'Keen-Eared', 'Ear-Lending', 'Overhearing', 'Ear-Wiggling', 'Listener', 'Monster-Ear', 'Hearer'],
    ['Pumped', 'Ripped', 'Muscly', 'Weight-Lifting', 'Training', 'Exercising', 'Bodybuilder', 'Iron-Pumper', 'Muscle Man'],
    ['Talky', 'Chatty', 'Talkative', 'Mom-Calling', 'Dialing', 'Ringing', 'Caller', 'Phone-Addict', 'Telephoner'],
    ['Triumphant', 'Peaceful', 'Victorious', 'Selfie-Making', 'Posing', 'Celebrating', 'Poser-Kid', 'Winner', 'Peace-Actvist'],
    ['Athletic', 'Olympic', 'Competitive', 'Serving', 'Defeating', 'Sporting', 'Player', 'Tennis-Pro', 'Athlete'],
    ['Twiggy', 'Biological', 'Leafy', 'Sprouting', 'Blossoming', 'Budding', 'Ent', 'Tree', 'Bush'],
    ['Heavenly', 'Feathered', 'Graceful', 'Flapping', 'Winging', 'Flailing', 'Angel', 'Bird', 'Aviator'],
    ['Busy', 'Efficient', 'Productive', 'Multitasking', 'High-Performing', 'Consulting', 'Manager', 'Multitasker', 'Headset-Guy'],
    ['Fishy', 'Maritime', 'Aquatic', 'Swimming', 'Fin-Waving', 'Bathing', 'Blowfish', 'Fish', 'Whale'],
    ['Hot', 'Warm', 'Steamy', 'Whistling', 'Boiling', 'Piping', 'Teapot', 'Kettle', 'Pot'],
],
top : [
    ['Bewigged', 'Uncombable', 'Curly', 'Hair-Dyeing', 'Blow-Drying', 'Shampooing', 'Granny', 'Perm', 'Wig'],
    ['Antenna-Headed', 'Connected', 'Extrinsic', 'Receiving', 'Signalling', 'Scouting', 'Alien', 'Martian', 'Visitor'],
    ['Juicy', 'Fresh', 'Ripe', 'Nourishing', 'Filling', 'Refreshing', 'Pear', 'Apple', 'Fruit'],
    ['Sun-Protected', 'Shadowed', 'Oriental', 'Sun-Fearing', 'Working', 'Harvesting', 'Tourist', 'Fisherman', 'Farmer'],
    ['Primitive', 'Bony', 'Wild', 'Bone-Collecting', 'Meat-Eating', 'Scoring', 'Galoot', 'Savage', 'Caveman'],
    ['Gastronomic', 'Culinary', 'Flavorful', 'Cooking', 'Baking', 'Frying', 'Chef', 'Cook', 'Foodie'],
    ['Free', 'Outdoor', 'Country', 'Cattle-Driving', 'Lassoing', 'Riding', 'Rancher', 'Texan', 'Herder'],
    ['Oldfashioned', 'Sophisticated', 'Traditional', 'Hat-Wearing', 'Gun-Slinging', 'Intimidating', 'Mafioso', 'Mobster', 'Gangster'],
    ['Medical', 'Caring', 'Analytical', 'Examining', 'Healing', 'Curing', 'Doctor', 'Dentist', 'Medic'],
    ['Drippy', 'Sweaty', 'Wet', 'Splashing', 'Leaking', 'Dripping', 'Splash', 'Droplet', 'Raindrop'],
    ['Allegedly-Dead', 'Iconic', 'Reborn', 'Rock\'n\'Rolling', 'Singing', 'Dancing', 'Elvis', 'Rockabilly', 'Imitator'],
    ['Holy', 'Worshipped', 'Divine', 'Blessing', 'Gleaming', 'Redeeming', 'Saint', 'Angel', 'Halo'],
    ['Native', 'Indigenous', 'Aboriginal', 'Defending', 'Feather-Wearing', 'Smoke-signaling', 'Hippie', 'Chief', 'Warrior'],
    ['Crowned', 'Godlike', 'Monarchical', 'Ruling', 'Reigning', 'Commanding', 'King', 'Monarch', 'Prince'],
    ['Wise', 'Powerful', 'Loyal', 'King-Serving', 'Fighting', 'Advising', 'Musketeer', 'Sorcerer', 'Magus'],
    ['Psychedelic', 'Edible', 'Poisonous', 'Mesmerizing', 'Intoxicating', 'Befuddling', 'Mushroom', 'Agaric', 'Fungus'],
    ['Uniformed', 'Official', 'Dutiful', 'Serving', 'Patroling', 'Arresting', 'Officer', 'Sarge', 'Deputee'],
    ['Noble', 'Fairy', 'Royal', 'Charming', 'Dreaming', 'Inspiring', 'Princess', 'Madam', 'Queen'],
    ['Edgy', 'Rowdy', 'Crazy', 'Revolting', 'Rioting', 'Provoking', 'Punk', 'Outlaw', 'Anarchist '],
    ['Fabulous', 'Mythical', 'Imaginary', 'Amazing', 'Fascinating', 'Enchanting', 'Unicorn', 'Chimera', 'Narwhal'],
    ['Cold', 'Chilly', 'Winterly', 'Freezing', 'Quivering', 'Shivering', 'Scandinavian', 'Bobble', 'McBobbleHat'],
],
bottom : [
    ['Lightweight', 'Fun', 'Floaty', 'Floating', 'Ascending', 'Rising', 'Balloon', 'Float', 'Aerostat'],
    ['Four-Toed', 'Shoeless', 'Barefoot', 'Wandering', 'Hiking', 'Lumbering', 'Hobbit', 'Wanderer', 'Hiker'],
    ['Clawed', 'Birdlike', 'Chirpy', 'Waddling', 'Clawing', 'Scraping', 'Birdman', 'Birdgirl', 'Claw'],
    ['Elegant', 'Upscale', 'Classy', 'Impressive', 'Posing', 'Imposing', 'Royal', 'Lord', 'Aristocrat'],
    ['Creepy', 'Uncanny', 'Monstrous', 'Crawling', 'Scuttling', 'Creeping', 'Spider', 'Spiderman', 'Tarantula'],
    ['Fishtailed', 'Finned', 'Natant', 'Mermaiding', 'Bathing', 'Splashing', 'Mermaid', 'Ariel', 'Orca'],
    ['Grounded', 'Leafy', 'Earthy', 'Growing', 'Gardening', 'Grass-rooting', 'Flower', 'Seedling', 'Groot'],
    ['Rhythmic', 'Musical', 'Tuneful', 'Rocking', 'Jamming', 'Shredding', 'Musician', 'Guitarist', 'Rocker'],
    ['Graceful', 'Heeled', 'Ladylike', 'Balancing', 'Modeling', 'Sashaying', 'Lady', 'Madame', 'Dame'],
    ['Weightless', 'Zero-G', 'Anti-Gravity', 'Levitating', 'Floating', 'Hovering', 'Ghost', 'Levitator', 'Hover-Ball'],
    ['Tentacled', 'Eight-Limbed', 'Tickly', 'Slithering', 'Sliding', 'Tickling', 'Octopus', 'Squid', 'Alien'],
    ['Bulb-Shaped', 'Electric', 'Voltaic', 'Electrifying', 'Glowing', 'Energizing', 'Bulb', 'Socket', 'Luminary'],
    ['Peg-Legged', 'One-Leg', 'Single-Shoed', 'Wobbling', 'Hobbling', 'Swaying', 'Pirate', 'Privateer', 'Veteran'],
    ['Hyperactive', 'Active', 'Energetic', 'Jumping', 'Hopping', 'Skipping', 'Hopper', 'Go-Getter', 'Jumper'],
    ['Freestyle', 'Fly', 'Skillful', 'Riding', 'Skateboarding', 'Kickflipping', 'Rider', 'Pro-Skater', 'Skateboarder'],
    ['Old-school', 'Inline', 'Four-Wheel', 'Skating', 'Rolling', 'Coasting', 'Inliner', 'Skater', '80s-Kid'],
    ['Fast', 'Downhill', 'Alpine', 'Skiing', 'Gliding', 'Skidding', 'Skier', 'Ski-Instructor', 'Snow-Slider'],
    ['Skilled', 'Quick', 'Nimble', 'Kicking', 'Dribbling', 'Scoring', 'Striker', 'Baller', 'Kicker'],
    ['Springy', 'Jumpy', 'Bouncy', 'Surprising', 'Flipping', 'Trolling', 'Surprise', 'Gagster', 'Joker'],
    ['Jaunty', 'Lively', 'Agile', 'Wandering', 'Strolling', 'Jogging', 'Nomad', 'Flaneur', 'Pilgrim'],
    ['Wheeled', 'Fast', 'Mobile', 'Driving', 'Cruising', 'Drifting', 'Wheelie', 'Ride', 'Carriage'],
],
};

WordCatalog.ADJECTIVE0 = 0;
WordCatalog.ADJECTIVE1 = 1;
WordCatalog.ADJECTIVE2 = 2;
WordCatalog.VERB0      = 3;
WordCatalog.VERB1      = 4;
WordCatalog.VERB2      = 5;
WordCatalog.NOUN0      = 6;
WordCatalog.NOUN1      = 7;
WordCatalog.NOUN2      = 8;
