// removeIf(production)
import { colorNames } from './color-names.js';
// endRemoveIf(production)

export const WordCatalog = {
color: colorNames,
face: [
    ['Cute', 'Whiskered', 'Proud', 'Purring', 'Straying', 'Meowing', 'Cat', 'Kitten', 'Tomcat'],
    ['Playful', 'Comical', 'Clownish', 'Entertaining', 'Amusing', 'Clowning', 'Bubble-Nose', 'Jester', 'Clown'],
    ['Shocked', 'Sad', 'Upset', 'Mourning', 'Sobbing', 'Grieving', 'Mourner', 'Griever', 'Lamenter'],
    ['Cheeky', 'Insider', 'Sassy', 'Winking', 'Blinking', 'Twinkling', 'Winker', 'Emoji', 'Smiley'],
    ['Thrifty', 'Frugal', 'Self-Made', 'Saving', 'Betting', 'Speculating', 'Risktaker', 'Moneymaker', 'Entrepreneur'],
    ['Ghostly', 'Transilvanian', 'Undead', 'Nipping', 'Biting', 'Nibbling', 'Vampire', 'Dracula', 'Bloodsucker'],
    ['Duckfaced', 'Short-Billed', 'Ducky', 'Chattering', 'Cackling', 'Quacking', 'Chick', 'Duck', 'Goose'],
    ['Naughty', 'Ingenious', 'Mischievous', 'Crafting', 'Planning', 'Devising', 'Ringleader', 'Mastermind', 'Instigator'],
    ['Impassioned', 'Amorous', 'Infatuated', 'Loving', 'Admiring', 'Desiring', 'Sweetheart', 'Romantic', 'Valentine'],
    ['Stunned', 'Speechless', 'Breathless', 'Resetting', 'Regenerating', 'Rebooting', 'Phantasm', 'Phantom', 'Ghost'],
    ['Mustached', 'Bearded', 'Trimmed', 'Grooming', 'Shaving', 'Trimming', 'Mustache', 'Barber', 'Beard'],
    ['Studious', 'Four-Eyed', 'Nerdy', 'Learning', 'Reading', 'Studying', 'Nerd', 'Geek', 'Genius'],
    ['One-Eyed', 'Monocular', 'Wide-Eyed', 'Eyeballing', 'Staring', 'Ogling', 'Odin', 'Cyclops', 'Monoid'],
    ['Adorable', 'Tame', 'Fluffy', 'Snuggling', 'Cuddling', 'Romping', 'Panda', 'Bear', 'Cub'],
    ['Tropical', 'Beaked', 'Exotic', 'Parroting', 'Chirping', 'Tweeting', 'Parrot', 'Parakeet', 'Tweety'],
    ['Good-Nosed', 'Wallowed', 'Snouted', 'Oinking', 'Truffling', 'Scenting', 'Piglet', 'Boar', 'Hog'],
    ['Eye-Patched', 'Gruff', 'Single-Eyed', 'Eye-Catching', 'Scowling', 'Frowning', 'Rover', 'McEyepatch', 'Buccaneer'],
    ['Happy', 'Cheerful', 'Jolly', 'Chuckling', 'Giggling', 'Laughing', 'Laugher', 'Giggler', 'Bon-Vivant'],
    ['Amazed', 'Impressed', 'Excited', 'Sparkling', 'Dazzling', 'Flashing', 'Starface', 'Fan', 'Wonderkid'],
    ['Swaggy', 'Funky', 'Cool', 'Sunbathing', 'Chilling', 'Relaxing', 'Hipster', 'Fashionista', 'Celebrity'],
    ['Funny', 'Goofy', 'Silly', 'Joking', 'Bantering', 'Quipping', 'Humorist', 'Jokester', 'Teaser'],
],
side : [
    ['Astronomical', 'Artificial', 'Metallic', 'Transmitting', 'Orbiting', 'Connecting', 'Satellite', 'Cyborg', 'Drone'],
    ['In-Love', 'Brave', 'Pierced', 'Braving', 'Defying', 'Enduring', 'Archer', 'Arrow', 'Cupid'],
    ['Bavarian', 'Sober', 'Malty', 'Brewing', 'Sipping', 'Partying', 'Lager', 'Beer-Fan', 'Octoberfest'],
    ['Protective', 'Punchy', 'Gloved', 'Boxing', 'Sparring', 'Slamming', 'Boxer', 'Champ', 'Hero'],
    ['Horned', 'Spiky', 'Pointy', 'Braving', 'Ramming', 'Pricking', 'Viking', 'Corsair', 'Hunk'],
    ['Pointy-Eared', 'Elfish', 'Puckish', 'Ear-Cocking', 'Listening', 'Sound-Sensing', 'Elf', 'Trekkie', 'Vulcan'],
    ['Pincerlike', 'Protective', 'Scuttling', 'Pinching', 'Snatching', 'Squeezing', 'Crab', 'Lobster', 'Crawfish'],
    ['Magical', 'Sorcerous', 'Foreseeing', 'Conjuring', 'Spell-Casting', 'Wizarding', 'Wizard', 'Healer', 'Sorcerer'],
    ['Two-Petaled', 'Sustainable', 'Organic', 'Flowering', 'Flourishing', 'Blooming', 'Flower', 'Plant', 'Sprout'],
    ['Sporty', 'Fit', 'Dynamic', 'Huddling', 'Quarterbacking', 'Tackling', 'Quarterback', 'Pigskin', 'Touchdown'],
    ['Hungry', 'Eager', 'Craving', 'Dining', 'Feasting', 'Eating', 'Foodie', 'Connoisseur', 'Gourmet'],
    ['Big-Eared', 'Bat-Eared', 'Keen-Eared', 'Ear-Lending', 'Overhearing', 'Ear-Wiggling', 'Listener', 'Monster-Ear', 'Hearer'],
    ['Pumped', 'Ripped', 'Muscly', 'Weightlifting', 'Training', 'Iron-Pumping', 'Bodybuilder', 'Athlete', 'Muscleman'],
    ['Talky', 'Chatty', 'Talkative', 'Calling', 'Dialing', 'Ringing', 'Self-Starter', 'Go-Getter', 'Hustler'],
    ['Triumphant', 'Peaceful', 'Victorious', 'Selfie-Taking', 'Posing', 'Celebrating', 'Coolio', 'Winner', 'Champion'],
    ['Athletic', 'Olympic', 'Competitive', 'Tiebreaking', 'Acing', 'Lobing', 'Ace', 'Tennis-Pro', 'Grand-Slam'],
    ['Twiggy', 'Branchy', 'Leafy', 'Sprouting', 'Blossoming', 'Budding', 'Branches', 'Tree', 'Bush'],
    ['Heavenly', 'Winged', 'Innocent', 'Flapping', 'Flying', 'Soaring', 'Angel', 'Bird', 'Guardian'],
    ['Busy', 'Hands-Free', 'Productive', 'Multitasking', 'Optimizing', 'Consulting', 'Manager', 'Multitasker', 'Organizer'],
    ['Marine', 'Maritime', 'Aquatic', 'Swimming', 'Fin-Waving', 'Diving', 'Shark', 'Fish', 'Whale'],
    ['Hot', 'Piping', 'Steamy', 'Whistling', 'Boiling', 'Brewing', 'Teapot', 'Kettle', 'Pot'],
],
top : [
    ['Bewigged', 'Uncombable', 'Curly', 'Hair-Dyeing', 'Blow-Drying', 'Shampooing', 'Toupee', 'Perm', 'Wig'],
    ['Antenna-Headed', 'Connected', 'Alert', 'Transmitting', 'Signalling', 'Connecting', 'Alien', 'Martian', 'Beacon'],
    ['Raw', 'Fresh', 'Ripe', 'Nourishing', 'Healthy', 'Refreshing', 'Pear', 'Apple', 'Fruit'],
    ['Sun-Hatted', 'Sun-Shaded', 'Oriental', 'Gardening', 'Farming', 'Harvesting', 'Harvester', 'Fisherman', 'Farmer'],
    ['Unbreakable', 'Untamed', 'Wild', 'Bone-Collecting', 'Meat-Loving', 'Roaming', 'Barbarian', 'Native', 'Caveman'],
    ['Gastronomic', 'Culinary', 'Flavorful', 'Cooking', 'Baking', 'Frying', 'Chef', 'Cook', 'Foodie'],
    ['Free', 'Outdoor', 'Country', 'Cattle-Driving', 'Lassoing', 'Rodeoing', 'Rancher', 'Cowboy', 'Herder'],
    ['Oldfashioned', 'Sophisticated', 'Traditional', 'Hat-Wearing', 'Investigating', 'Distinguishing', 'Detective', 'Gentleman', 'Cavalier'],
    ['Medical', 'Caring', 'Analytical', 'Examining', 'Healing', 'Curing', 'Doctor', 'Surgeon', 'Medic'],
    ['Drippy', 'Sweaty', 'Wet', 'Exercising', 'Soaking', 'Dripping', 'Splash', 'Droplet', 'Raindrop'],
    ['Legendary', 'Iconic', 'Fabulous', 'Rock\'n\'Rolling', 'Pompadouring', 'Imitating', 'Elvis', 'Rockabilly', 'Imitator'],
    ['Holy', 'Sacred', 'Divine', 'Blessing', 'Divining', 'Forseeing', 'Saint', 'Spirit', 'Halo'],
    ['Feathered', 'Indigenous', 'Tribal', 'Earth-Respecting', 'Feather-Wearing', 'Smoke-signaling', 'Pagan', 'Chief', 'Warrior'],
    ['Regally', 'Princely', 'Stately', 'Ruling', 'Reigning', 'Commanding', 'Ruler', 'Monarch', 'Majesty'],
    ['Wise', 'Powerful', 'Loyal', 'Counseling', 'Representing', 'Advising', 'Musketeer', 'Alchemist', 'Magician'],
    ['Psychedelic', 'Edible', 'Trippy', 'Mesmerizing', 'Hypnotizing', 'Captivating', 'Mushroom', 'Spore', 'Fungus'],
    ['Uniformed', 'Official', 'Dutiful', 'Serving', 'Patrolling', 'Protecting', 'Officer', 'Sarge', 'Deputee'],
    ['Noble', 'Gracious', 'Royally', 'Charming', 'Dreaming', 'Inspiring', 'Princess', 'Empress', 'Queen'],
    ['Edgy', 'Funky', 'Wicked', 'Nonconforming', 'Challenging', 'Stirring', 'Rebel', 'Maverick', 'Individualist '],
    ['Fabulous', 'Mythical', 'Imaginary', 'Amazing', 'Fascinating', 'Enchanting', 'Unicorn', 'Chimera', 'Narwhal'],
    ['Cold', 'Chilly', 'Winterly', 'Freezing', 'Quivering', 'Shivering', 'Beanie', 'Bobble', 'McBobbleHat'],
],
bottom : [
    ['Lightweight', 'Fun', 'Floaty', 'Floating', 'Ascending', 'Rising', 'Balloon', 'Float', 'Aerostat'],
    ['Four-Toed', 'Shoeless', 'Barefoot', 'Wandering', 'Hiking', 'Lumbering', 'Hobbit', 'Wanderer', 'Hiker'],
    ['Clawed', 'Birdlike', 'Chirpy', 'Waddling', 'Clawing', 'Scraping', 'Birdman', 'Birdgirl', 'Claw'],
    ['Elegant', 'Upscale', 'Classy', 'Impressive', 'Posing', 'Imposing', 'Royal', 'Lord', 'Aristocrat'],
    ['Creepy', 'Uncanny', 'Monstrous', 'Crawling', 'Scuttling', 'Creeping', 'Spider', 'Spiderman', 'Tarantula'],
    ['Fishtailed', 'Finned', 'Natant', 'Mermaiding', 'Bathing', 'Splashing', 'Mermaid', 'Ariel', 'Orca'],
    ['Grounded', 'Leafy', 'Earthy', 'Growing', 'Gardening', 'Grass-rooting', 'Flower', 'Seedling', 'Groot'],
    ['Rhythmic', 'Musical', 'Tuneful', 'Rocking', 'Jamming', 'Shredding', 'Musician', 'Guitarist', 'Rocker'],
    ['Graceful', 'Heeled', 'Ladylike', 'Balancing', 'Modeling', 'Sashaying', 'Lady', 'Madame', 'Dame'],
    ['Weightless', 'Zero-G', 'Anti-Gravity', 'Levitating', 'Floating', 'Hovering', 'Ghost', 'Levitator', 'Hover-Ball'],
    ['Tentacled', 'Eight-Limbed', 'Tickly', 'Slithering', 'Sliding', 'Tickling', 'Octopus', 'Squid', 'Alien'],
    ['Bulb-Shaped', 'Electric', 'Voltaic', 'Electrifying', 'Glowing', 'Energizing', 'Bulb', 'Socket', 'Luminary'],
    ['Peg-Legged', 'One-Leg', 'Single-Shoed', 'Wobbling', 'Hobbling', 'Swaying', 'Pirate', 'Privateer', 'Veteran'],
    ['Hyperactive', 'Active', 'Energetic', 'Jumping', 'Hopping', 'Skipping', 'Hopper', 'Go-Getter', 'Jumper'],
    ['Freestyle', 'Fly', 'Skillful', 'Riding', 'Skateboarding', 'Kickflipping', 'Rider', 'Pro-Skater', 'Skateboarder'],
    ['Old-school', 'Inline', 'Four-Wheel', 'Skating', 'Rolling', 'Coasting', 'Inliner', 'Skater', '80s-Kid'],
    ['Fast', 'Downhill', 'Alpine', 'Skiing', 'Gliding', 'Skidding', 'Skier', 'Ski-Instructor', 'Snow-Slider'],
    ['Skilled', 'Quick', 'Nimble', 'Kicking', 'Dribbling', 'Scoring', 'Striker', 'Baller', 'Kicker'],
    ['Springy', 'Jumpy', 'Bouncy', 'Surprising', 'Flipping', 'Trolling', 'Surprise', 'Gagster', 'Joker'],
    ['Jaunty', 'Lively', 'Agile', 'Wandering', 'Strolling', 'Jogging', 'Nomad', 'Flaneur', 'Pilgrim'],
    ['Wheeled', 'Fast', 'Mobile', 'Driving', 'Cruising', 'Drifting', 'Wheelie', 'Ride', 'Carriage'],
],
};

WordCatalog.ADJECTIVE0 = 0;
WordCatalog.ADJECTIVE1 = 1;
WordCatalog.ADJECTIVE2 = 2;
WordCatalog.VERB0      = 3;
WordCatalog.VERB1      = 4;
WordCatalog.VERB2      = 5;
WordCatalog.NOUN0      = 6;
WordCatalog.NOUN1      = 7;
WordCatalog.NOUN2      = 8;
